Fixes io.vertx.ext.dropwizard.MetricsTest.testEventBusMetricsHandlerRegexMatchWithIdentifier
java.lang.AssertionError: null (count) expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:431)
	at io.vertx.ext.dropwizard.MetricsTest.assertCount(MetricsTest.java:1299)
	at io.vertx.ext.dropwizard.MetricsTest.testEventBusMetricsHandlerRegexMatchWithIdentifier(MetricsTest.java:902)

allHandlersLatch should be updated after the consumer handler is done otherwise metrics might not be updated in time.