Fix MetricsTest for cleanable clients
In CI, there was an ISE thrown:

Error:  io.vertx.ext.dropwizard.tests.MetricsTest.testNetMetricsOnClose -- Time elapsed: 0.012 s <<< ERROR!
java.lang.IllegalStateException
	at io.vertx.core@5.1.0-SNAPSHOT/io.vertx.core.impl.CleanableObject.getOrDie(CleanableObject.java:61)
	at io.vertx.core@5.1.0-SNAPSHOT/io.vertx.core.net.impl.tcp.CleanableNetClient.getMetrics(CleanableNetClient.java:89)
	at io.vertx.metrics.dropwizard@5.1.0-SNAPSHOT/io.vertx.ext.dropwizard.impl.AbstractMetrics.unwrap(AbstractMetrics.java:48)
	at io.vertx.metrics.dropwizard@5.1.0-SNAPSHOT/io.vertx.ext.dropwizard.impl.MetricsServiceImpl.getMetricsSnapshot(MetricsServiceImpl.java:32)
	at io.vertx.metrics.dropwizard.tests/io.vertx.ext.dropwizard.tests.MetricsTest.testNetMetricsOnClose(MetricsTest.java:796)

This was due to the changes in https://github.com/eclipse-vertx/vert.x/pull/6109

 In this test, we can use the clientBaseName instead of the client reference. This is functionally equivalent and robust.

Signed-off-by: Thomas Segismont <tsegismont@gmail.com>